version: "3"

services:
  core_api_client:
    build: ./
    image: core_api_client:latest-apine
    env_file: .env
    ports:
      - "8008:80"
    networks:
      - frontend

networks:
  frontend:
    external: true
